/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as OpenVsClosedRouteImport } from './routes/open-vs-closed'
import { Route as NextDecadeRouteImport } from './routes/next-decade'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HumanityRouteImport } from './routes/humanity'
import { Route as HowAiWorksRouteImport } from './routes/how-ai-works'
import { Route as GeopoliticsRouteImport } from './routes/geopolitics'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DataWallRouteImport } from './routes/data-wall'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AgiAsiRouteImport } from './routes/agi-asi'
import { Route as IndexRouteImport } from './routes/index'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenVsClosedRoute = OpenVsClosedRouteImport.update({
  id: '/open-vs-closed',
  path: '/open-vs-closed',
  getParentRoute: () => rootRouteImport,
} as any)
const NextDecadeRoute = NextDecadeRouteImport.update({
  id: '/next-decade',
  path: '/next-decade',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanityRoute = HumanityRouteImport.update({
  id: '/humanity',
  path: '/humanity',
  getParentRoute: () => rootRouteImport,
} as any)
const HowAiWorksRoute = HowAiWorksRouteImport.update({
  id: '/how-ai-works',
  path: '/how-ai-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GeopoliticsRoute = GeopoliticsRouteImport.update({
  id: '/geopolitics',
  path: '/geopolitics',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DataWallRoute = DataWallRouteImport.update({
  id: '/data-wall',
  path: '/data-wall',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AgiAsiRoute = AgiAsiRouteImport.update({
  id: '/agi-asi',
  path: '/agi-asi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agi-asi': typeof AgiAsiRoute
  '/companies': typeof CompaniesRoute
  '/compute': typeof ComputeRoute
  '/data-wall': typeof DataWallRoute
  '/games': typeof GamesRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/how-ai-works': typeof HowAiWorksRoute
  '/humanity': typeof HumanityRoute
  '/infrastructure': typeof InfrastructureRoute
  '/learn': typeof LearnRoute
  '/next-decade': typeof NextDecadeRoute
  '/open-vs-closed': typeof OpenVsClosedRoute
  '/sources': typeof SourcesRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agi-asi': typeof AgiAsiRoute
  '/companies': typeof CompaniesRoute
  '/compute': typeof ComputeRoute
  '/data-wall': typeof DataWallRoute
  '/games': typeof GamesRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/how-ai-works': typeof HowAiWorksRoute
  '/humanity': typeof HumanityRoute
  '/infrastructure': typeof InfrastructureRoute
  '/learn': typeof LearnRoute
  '/next-decade': typeof NextDecadeRoute
  '/open-vs-closed': typeof OpenVsClosedRoute
  '/sources': typeof SourcesRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agi-asi': typeof AgiAsiRoute
  '/companies': typeof CompaniesRoute
  '/compute': typeof ComputeRoute
  '/data-wall': typeof DataWallRoute
  '/games': typeof GamesRoute
  '/geopolitics': typeof GeopoliticsRoute
  '/how-ai-works': typeof HowAiWorksRoute
  '/humanity': typeof HumanityRoute
  '/infrastructure': typeof InfrastructureRoute
  '/learn': typeof LearnRoute
  '/next-decade': typeof NextDecadeRoute
  '/open-vs-closed': typeof OpenVsClosedRoute
  '/sources': typeof SourcesRoute
  '/use-cases': typeof UseCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agi-asi'
    | '/companies'
    | '/compute'
    | '/data-wall'
    | '/games'
    | '/geopolitics'
    | '/how-ai-works'
    | '/humanity'
    | '/infrastructure'
    | '/learn'
    | '/next-decade'
    | '/open-vs-closed'
    | '/sources'
    | '/use-cases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agi-asi'
    | '/companies'
    | '/compute'
    | '/data-wall'
    | '/games'
    | '/geopolitics'
    | '/how-ai-works'
    | '/humanity'
    | '/infrastructure'
    | '/learn'
    | '/next-decade'
    | '/open-vs-closed'
    | '/sources'
    | '/use-cases'
  id:
    | '__root__'
    | '/'
    | '/agi-asi'
    | '/companies'
    | '/compute'
    | '/data-wall'
    | '/games'
    | '/geopolitics'
    | '/how-ai-works'
    | '/humanity'
    | '/infrastructure'
    | '/learn'
    | '/next-decade'
    | '/open-vs-closed'
    | '/sources'
    | '/use-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgiAsiRoute: typeof AgiAsiRoute
  CompaniesRoute: typeof CompaniesRoute
  ComputeRoute: typeof ComputeRoute
  DataWallRoute: typeof DataWallRoute
  GamesRoute: typeof GamesRoute
  GeopoliticsRoute: typeof GeopoliticsRoute
  HowAiWorksRoute: typeof HowAiWorksRoute
  HumanityRoute: typeof HumanityRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LearnRoute: typeof LearnRoute
  NextDecadeRoute: typeof NextDecadeRoute
  OpenVsClosedRoute: typeof OpenVsClosedRoute
  SourcesRoute: typeof SourcesRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-vs-closed': {
      id: '/open-vs-closed'
      path: '/open-vs-closed'
      fullPath: '/open-vs-closed'
      preLoaderRoute: typeof OpenVsClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-decade': {
      id: '/next-decade'
      path: '/next-decade'
      fullPath: '/next-decade'
      preLoaderRoute: typeof NextDecadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humanity': {
      id: '/humanity'
      path: '/humanity'
      fullPath: '/humanity'
      preLoaderRoute: typeof HumanityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-ai-works': {
      id: '/how-ai-works'
      path: '/how-ai-works'
      fullPath: '/how-ai-works'
      preLoaderRoute: typeof HowAiWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geopolitics': {
      id: '/geopolitics'
      path: '/geopolitics'
      fullPath: '/geopolitics'
      preLoaderRoute: typeof GeopoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-wall': {
      id: '/data-wall'
      path: '/data-wall'
      fullPath: '/data-wall'
      preLoaderRoute: typeof DataWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agi-asi': {
      id: '/agi-asi'
      path: '/agi-asi'
      fullPath: '/agi-asi'
      preLoaderRoute: typeof AgiAsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgiAsiRoute: AgiAsiRoute,
  CompaniesRoute: CompaniesRoute,
  ComputeRoute: ComputeRoute,
  DataWallRoute: DataWallRoute,
  GamesRoute: GamesRoute,
  GeopoliticsRoute: GeopoliticsRoute,
  HowAiWorksRoute: HowAiWorksRoute,
  HumanityRoute: HumanityRoute,
  InfrastructureRoute: InfrastructureRoute,
  LearnRoute: LearnRoute,
  NextDecadeRoute: NextDecadeRoute,
  OpenVsClosedRoute: OpenVsClosedRoute,
  SourcesRoute: SourcesRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
